name: Process Exclusion Requests

on:
  issue_comment:
    types: [created]

permissions:
  issues: write

jobs:
  exclusion:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install python dependencies
      run: |
        pwd
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run script
      run: |
        python './.github/workflows/exclusion.py' --issue_id ${{ github.event.issue.number }} --comment_id ${{ github.event.comment.id }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
