name: VBA-Scan-And-Suggest

on:
  workflow_dispatch:
  schedule:
  - cron:  '30 */6 * * *'

permissions:
  issues: write  # Ensure the token has permission to create issues

jobs:
  scan-and-suggest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install python dependencies
      run: |
        pwd
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Check Git Config
      run: |
        git config --show-scope --get core.autocrlf
    - name: Run script
      run: |
        python './.github/workflows/scan_and_suggest.py'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
