name: 'Mark stale issues'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * *' # Runs every day at 17h UTC

jobs:
  stale:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      contents: write

    steps:
    - name: Run stale action
      uses: actions/stale@v9
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        operations-per-run: 200
        stale-issue-message: 'This issue has been marked as stale due to inactivity for 30 days. If you need help or have any questions, feel free to ask.'
        days-before-stale: 30
        days-before-close: 30
        stale-issue-label: 'stale'
        only-labels: 'external'
        close-issue-message: 'Closing this issue due to prolonged inactivity. You can still fix this issue, but it won''t be tracked here.'
        remove-stale-when-updated: true
        close-issue-reason: 'not_planned'
